include_guard()

if(CMAKE_CXX_COMPILER_ID STREQUAL "MSVC")
	set(XRAD_ThirdParty $ENV{XRADThirdParty} CACHE PATH "XRAD third party root directory.")
	if("${XRAD_ThirdParty}" STREQUAL "")
		message(FATAL_ERROR "Please, specify XRAD third party root directory (XRAD_ThirdParty).")
	endif()
elseif(CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
	set(XRAD_ThirdParty $ENV{XRADThirdParty} CACHE PATH "XRAD third party install directory.")
	if("${XRAD_ThirdParty}" STREQUAL "")
		message(FATAL_ERROR "Please, specify XRAD third party install directory (XRAD_ThirdParty).")
	endif()
else()
	message(FATAL_ERROR "Unsupported CMAKE_CXX_COMPILER_ID: \"${CMAKE_CXX_COMPILER_ID}\".")
endif()
